### PR TITLE
Expose RasterSource resample methods through configuration options

### LINKED ISSUE #150: Artefacts with hillshade MAML operation
When I use fhillshade MAML operation from the DEM data, It have artefacts on the GetMap result. On the example below, we see vertical and horizontal lines. The request GetMap use projection of original data (EPSG:3857) and a color-maps style.

`
SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=**EPSG:3857**&BBOX=-8212121.0951458206,10994397.212170906,-8204445.5172946611,11001294.913466308&WIDTH=967&HEIGHT=869&LAYERS=arcticdem2mhillshade&STYLES=greyscalemap&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE&
`
image

We see the same thing for a GetMap request that uses a different projection than the original data.
`
SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=**EPSG:3978**&BBOX=780813.0364727308,2393130.123206886,786953.49875365547,2398648.2842432079&WIDTH=967&HEIGHT=869&LAYERS=arcticdem2mhillshade&STYLES=greyscalemap&EXCEPTIONS=XML&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE
`
image

We see the same thing with color-ramps style.

image

### LINKED ISSUE #229: Configurable ResampleMethod in source definitions
Connects: #150

`SimpleSource` or `MapAlgebraSource` (for each source) should have an option to configure the resample method. Currently all instances default to `NearestNeighbor` resample method which probably cause artifacts in #150

### PR DESCRIPTION
**Pull request by pomadchin**
## Overview

This PR adds resample method as a cofigurable application.conf option

### Checklist

- [x] Description of PR is in an appropriate section of the CHANGELOG and grouped with similar changes if possible

### Demo

bilinear-nn

It's also possible to view it via QGIS & a GeoTrellis server instance:

```bash
$ ./sbt
> project ogcExamples
> run --public-url http://localhost:9000/
```

Select the `us-ned-hillshade` WMS/WMTS/WCS layer!

Closes #229
Closes #150

### CODE REVIEW

File: core/src/test/scala/geotrellis/server/LayerExtentTest.scala [hunk 1]
```diff
@@ -16,32 +16,24 @@
...
-import scala.util.Random
 import scala.concurrent.ExecutionContext
 
-
 class LayerExtentTest extends FunSuite with Matchers {
   implicit val cs = cats.effect.IO.contextShift(ExecutionContext.global)
 
   test("ability to read a selected extent") {
-    val rt = ResourceTile("8x8.tif")
+    val rt = ResourceTile("8x8.tif", NearestNeighbor)
```
Comment (pomadchin) [inline core/src/test/scala/geotrellis/server/LayerExtentTest.scala]: Hm, mb NN should be a default method everywhere? @CloudNiner

File: ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+  implicit class TypeRefinement(self: Interpreted[Result]) {
+    def as[T: ClassTag]: Interpreted[T] = self match {
+      case Valid(r) => r.as[T]
+      case i @ Invalid(_) => i
+    }
+  }
+
+  // https://github.com/geotrellis/geotrellis-server/issues/150
+  describe("HillshadeSpec") {
+    ignore("RasterSource reproject hillshade") {
```
Comment (pomadchin) [inline ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala]: Ignore, since it is read from the S3 catalog. Mb we can think of a better test later (?)

File: ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala [hunk 3]
```diff
@@ -51,6 +51,7 @@ trait OgcSource {
   def metadata: RasterMetadata
   def attributes: Map[String, String]
   def time: Option[ZonedDateTime]
+  def resampleMethod: ResampleMethod
```
Comment (CloudNiner) [inline ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala]: Is this part of the OGC definitions for "what an OGC layer is capable of" and does this attribute meet the requirements for inclusion defined in the docstring? Just double checking that this belongs as part of this trait so that we don't start to hang attributes off of OgcSource that make it less composable.

File: ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala [hunk 4]
```diff
@@ -17,37 +17,37 @@
...
 }
 
 case class SimpleSourceConf(
   name: String,
   title: String,
   sources: List[String],
   defaultStyle: Option[String],
-  styles: List[StyleConf]
+  styles: List[StyleConf],
+  resampleMethod: ResampleMethod
```
Comment (CloudNiner) [inline ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala]: Should this default instead to "nearest-neighbor" so that existing confs are backwards compatible rather than forcing each user to make a choice about each layer they've defined? A default would also reduce the burden on new users when generating their first conf.

I don't feel strongly about it, just thinking through the implications of a change like this. If we leave it as is, we should definitely clarify in the changelog that this change is breaking for existing confs and point users to the list of available options and even perhaps what the implications of each option are, if we have that info available.

File: ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala (hunk 2 above)
Comment (CloudNiner) [reply ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala]: Ha. I was just about to comment that this test needs credentials. Beat me to it. 

In reality, doesn't this test belong in MAML or GeoTrellis since it doesn't have an GT server components at all? Perhaps one of those repos is better setup for these types of tests.

Comment (pomadchin) [reply ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala]: Probably should live eventually in GeoTrellis; wanted to capture it at least somewhere.

File: ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala (hunk 3 above)
Comment (pomadchin) [reply ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala]: Yes, I think it is a 'what method for all resampling operation this raster source would use'; checkout also #229

File: ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala (hunk 4 above)
Comment (pomadchin) [reply ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala]: I also didn't feel strong; see https://github.com/geotrellis/geotrellis-server/pull/233#discussion_r396420013 :D I'll add a default behavior than, since I also had a feeling about that but was not sure :+1:

Comment (CloudNiner) [reply ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala]: Oh I missed that comment -- :great-minds:. Adding a default sounds good, just leave the non-default new layer in the application.conf to demonstrate that it's possible. Maybe link to the non-default layer in the changelog so users can see an example at a glance?

File: ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala (hunk 3 above)
Comment (CloudNiner) [reply ogc/src/main/scala/geotrellis/server/ogc/OgcSource.scala]: 👍

File: ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala (hunk 2 above)
Comment (CloudNiner) [reply ogc-example/src/test/scala/geotrellis/server/HillshadeSpec.scala]: 👍 perhaps make an issue in locationtech/geotrellis? We might never get to it, but then its at least documented somewhere that its something we wanted to do...

File: ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala (hunk 4 above)
Comment (pomadchin) [reply ogc-example/src/main/scala/geotrellis/server/ogc/conf/OgcSourceConf.scala]: @CloudNiner :+1:

File: ogc-example/src/main/resources/application.conf [hunk 5]
```diff
@@ -334,6 +338,33 @@ layers = {
             }
         ]
     }
+    us-ned-hillshade = {
+      type = "mapalgebrasourceconf"
+      name = "us-ned-hillshade"
+      title = "US NED Hillshade"
+      resample-method = "bilinear"
```
Comment (pomadchin) [inline ogc-example/src/main/resources/application.conf]: `resample-method` is a new optional parameter, that's the usage example.

**Comment by CloudNiner** [comment]
👍 still LGTM!

**Comment by pomadchin** [comment]
Added an issue to move HillshadeSpecs from this repo into the GeoTrellis core. Mergin once CircleCI is happy!
